"""Altered Artist Table.

Revision ID: 15138506b107
Revises: 0912dd422cc7
Create Date: 2022-06-02 19:43:58.428220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15138506b107'
down_revision = '0912dd422cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean, nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=320), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
